#####################################################################################################################
## Set the message that will be displayed to players when they try to run a CTP command, but don't have permission ##
#####################################################################################################################
no-permission-message: "&cYou don't have permission!"


#####################################################################################################################
## Set the name of the world (case-sensitive) that you want the plugin to be active in. This means that the        ##
## specified world will be the only world that can have block locations set in it. When the command is run, all    ##
## players will still be teleported, regardless of the world they are currently in.                                ##
#####################################################################################################################
world-name: 'world'


#####################################################################################################################
## When the commands "/ctp tpall", "/ctp return", "/ctp warn", or "/ctp reload" are executed,                      ##
## should all CTP admins be advised about who executed the command?                                                ##
#####################################################################################################################
warn-admins-on-execute: false


#####################################################################################################################
## When all players are teleported or returned, should all CTP admins be advised of the success or failure         ##
## of the teleportation/returning? Setting this value to false will still cause the command executor to be warned  ##
##                                                                                                                 ##
## Note: if a player joins the server while tpall is active, and there isn't a block location available for them,  ##
## all CTP admins will be warned accordingly.                                                                      ##
#####################################################################################################################
warn-admins-on-teleport: false


#####################################################################################################################
## You can set the warning message that will be sent                                                               ##
## as a title message to all teleportable players using /ctp warn                                                  ##
#####################################################################################################################
warning-title: '&a&lChurch is about to begin'
warning-subtitle: '&lYou will be teleported to your seat shortly'


#####################################################################################################################
## Should players be sent a chat message after being teleported?                                                   ##
## Note: this includes if the tpall command is active, and a teleportable player joins the server.                 ##
#####################################################################################################################
message-players-on-tp: true


#####################################################################################################################
## If above is true, you can set the specific message you want them to be sent                                     ##
#####################################################################################################################
on-tp-messages:
  - '&aYou have been teleported to your seat and are frozen until church is over.'
# - 'You can specify multiple message lines to be sent if you want'


#####################################################################################################################
## When the players are teleported, all commands will be disabled for those players except for these commands:     ##
## (you must enter the commands without a '/' preceding them)                                                      ##
#####################################################################################################################
enabled-commands:
  - 'bible'
  - 'openbible'


#####################################################################################################################
## When a player is teleported, and they attempt to execute a                                                      ##
## non-exempt command, what message should they be sent?                                                           ##
#####################################################################################################################
command-not-allowed-message: "&c&lHey! &3Sorry, you can't use that command right now."


#####################################################################################################################
## Should players be sent a chat message after being returned?                                                     ##
#####################################################################################################################
message-players-on-return: true



#####################################################################################################################
## If the above is true, you can set the specific message you want them to be sent                                 ##
#####################################################################################################################
on-return-messages:
  - '&aChurch is over and you have been returned to your original location'
# - 'You can specify multiple message lines to be sent if you want'

bungeecord-channel: 'channel'

# ***NOT IMPLEMENTED, PLEASE DISREGARD***
#####################################################################################################################
## (not required) Set the coordinates of the location that all teleported players should look at when              ##
## they are teleported. This will force players to look directly at the center of the specified                    ##
## location. Enter the location as a comma-separated string with no spaces, like: "55,70,125" (no decimals).       ##
## This location will be found in the world specified in 'world-name'                                              ##
## Note: leaving an empty string in this value will cause players to look in the direction they were pre-teleport  ##
#####################################################################################################################
center-viewing-block: ""
