# Set the message that will be displayed to players when they try to run a CTP command, but don't have permission
no-permission-message: "&cYou don't have permission!"

# When the commands "/ctp tpall", "/ctp return", "/ctp warn", or "/ctp reload" are executed,
# should all CTP admins be warned about who executed the command?
warn-admins-on-execute: true

# When all players are teleported or returned, should all CTP admins be advised of the success or failure
# of the teleportation/returning?
warn-admins-on-teleport: true

# You can set the warning message that will be sent as a title message to all teleportable players using /ctp warn
warning-title: '&a&lChurch is about to begin'
warning-subtitle: '&lYou will be teleported to your seat shortly'

# Should players be sent a chat message after being teleported?
message-players-on-tp: true

# If above is true, you can set the specific message you want them to be sent
on-tp-messages:
  - '&aYou have been teleported to your seat and are frozen until church is over.'
# - 'You can specify multiple message lines to be sent if you want'

# Should players be sent a chat message after being returned?
message-players-on-return: true

# If the above is true, you can set the specific message you want them to be sent
on-return-messages:
  - '&aChurch is over and you have been returned to your original location'
# - 'You can specify multiple message lines to be sent if you want'

